### ISSUE TITLE
Hold Space Bar down to increase DepthCharge time until explosion

### ISSUE THREAD

**Issue by belovachap** [belovachap/SubBoomUnity#14]
At the moment DepthCharges exist for the same amount of time (I think 10 seconds) and then explode. The game mechanic should be to count how long the player has held down the space bar and then set the DepthCharge explosion time to that value once the player lifts up on the space bar. This make the game a bit more challenging as the player has to gauge how deep they want the depth charge to go and then dodge torpedos while trying to release in the right spot to destroy the targeted submarines.

One thing to consider: if the player presses down on the space bar and immediately lifts up should the depth charge explode immediately (killing the player)?

**Comment by spicewooddev** [comment]
Working on this right now. So far, the depth charges will descend while the space key is held and will explode when released. However, it looks like I'm getting the same game-crashing bug as when a submarine dies by its own exploding charge, so I'll have to see how to fix that.

**Comment by spicewooddev** [comment]
Maybe because of isTouching() ? That's the only obvious thing I can think of, but I'm not too sure. I will make a branch for the .cs file I have so far in case you want to take a look.
